
engine_git: https://github.com/ialbert/biostar-central.git
engine_dir:  "{{ main_dir | default('/export/www/biostar-central') }}"

bin_dir: "/export/bin"
src_dir: "/export/src"
ref_dir: "/export/refs"

# Location of old database on local machine
local_old: "{{ local_old_db }}"

# Location to the old database in remote node
# This is the destination where local_old will be copied.
remote_old: "{{ engine_dir }}/export/sql/{{ local_old_db | basename }}"

django_settings_module: "conf.run.site_settings"

# Installs recipe dependencies.
install: False
restart: False
reset: False
backup: False


conda_activate: "/home/www/miniconda3/envs/engine/bin/activate"
conda_env: "engine"

conda_url: https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
conda_dir: "~/miniconda3"

conda_environments:
  - { name: "{{ conda_env }}", python_version: 3.6}
  - { name: test, python_version: 3.6}
  - { name: py2, python_version: 2}

conda_modify_path: yes

conda_rcfile: "~/.bashrc"

conda_add_condarc: yes
